# Generated by Django 3.0.5 on 2020-05-25 19:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField(verbose_name='ссылка на изображение')),
                ('about_img', models.TextField(verbose_name='описание')),
                ('where', models.CharField(max_length=20, verbose_name='координаты')),
            ],
            options={
                'verbose_name': 'Скриншот',
                'verbose_name_plural': 'Скриншоты',
            },
        ),
        migrations.CreateModel(
            name='Showcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MyMapView_title', models.CharField(max_length=100, verbose_name='название статьи')),
                ('MyMapView_text', models.TextField(verbose_name='текст статьи')),
                ('Pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата публикации')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='имя автора')),
                ('comment_text', models.CharField(max_length=300, verbose_name='текст комментария')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата публикации')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyMapView.Showcode')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
