# Generated by Django 3.0.5 on 2020-05-27 11:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MyMapView', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий к статье', 'verbose_name_plural': 'Комментарии к статье'},
        ),
        migrations.CreateModel(
            name='Imgcomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='имя автора')),
                ('comment_text', models.CharField(max_length=300, verbose_name='текст комментария')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата публикации')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyMapView.Image')),
            ],
            options={
                'verbose_name': 'Комментарий к скриншоту',
                'verbose_name_plural': 'Комментарии к скриншоту',
            },
        ),
    ]
